[package]
name = "mozidb"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
json = "0.12.4"
rusqlite = { version = "0.37.0", features = ["bundled"] }
snap = "1.1.1"

[profile.samply]
inherits = "release"
debug = true
